"""added cars

Revision ID: 221d73ace583
Revises: 51ae42d8bee9
Create Date: 2016-06-09 18:55:08.617646

"""

# revision identifiers, used by Alembic.
revision = '221d73ace583'
down_revision = '51ae42d8bee9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('proprietor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cars_make', 'cars', ['make'], unique=False)
    op.create_index('ix_cars_model', 'cars', ['model'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_model', 'cars')
    op.drop_index('ix_cars_make', 'cars')
    op.drop_table('cars')
    ### end Alembic commands ###
