"""initial migration

Revision ID: d9635d692f3
Revises: None
Create Date: 2016-06-14 18:02:06.776183

"""

# revision identifiers, used by Alembic.
revision = 'd9635d692f3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('proprietor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cars_make', 'cars', ['make'], unique=False)
    op.create_index('ix_cars_model', 'cars', ['model'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_model', 'cars')
    op.drop_index('ix_cars_make', 'cars')
    op.drop_table('cars')
    op.drop_index('ix_users_name', 'users')
    op.drop_index('ix_users_firstname', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    ### end Alembic commands ###
